mv 10c.png 10_clubs.png
mv 10d.png 10_diamonds.png
mv 10h.png 10_hearts.png
mv 10s.png 10_spades.png
mv 2c.png  2_clubs.png
mv 2d.png  2_diamonds.png
mv 2h.png  2_hearts.png
mv 2s.png  2_spades.png
mv 3c.png  3_clubs.png
mv 3d.png  3_diamonds.png
mv 3h.png  3_hearts.png
mv 3s.png  3_spades.png
mv 4c.png  4_clubs.png
mv 4d.png  4_diamonds.png
mv 4h.png  4_hearts.png
mv 4s.png  4_spades.png
mv 5c.png  5_clubs.png
mv 5d.png  5_diamonds.png
mv 5h.png  5_hearts.png
mv 5s.png  5_spades.png
mv 6c.png  6_clubs.png
mv 6d.png  6_diamonds.png
mv 6h.png  6_hearts.png
mv 6s.png  6_spades.png
mv 7c.png  7_clubs.png
mv 7d.png  7_diamonds.png
mv 7h.png  7_hearts.png
mv 7s.png  7_spades.png
mv 8c.png  8_clubs.png
mv 8d.png  8_diamonds.png
mv 8h.png  8_hearts.png
mv 8s.png  8_spades.png
mv 9c.png  9_clubs.png
mv 9d.png  9_diamonds.png
mv 9h.png  9_hearts.png
mv 9s.png  9_spades.png
mv ac.png  ace_clubs.png
mv ad.png  ace_diamonds.png
mv ah.png  ace_hearts.png
mv as.png  ace_spades.png
mv jc.png  jack_clubs.png
mv jd.png  jack_diamonds.png
mv jh.png  jack_hearts.png
mv js.png  jack_spades.png
mv kc.png  king_clubs.png
mv kd.png  king_diamonds.png
mv kh.png  king_hearts.png
mv ks.png  king_spades.png
mv qc.png  queen_clubs.png
mv qd.png  queen_diamonds.png
mv qh.png  queen_hearts.png
mv qs.png  queen_spades.png
